version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  wait-for-mysql:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_ADDRESS=db
